// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// matrix_binary_search
NumericVector matrix_binary_search(NumericMatrix score_mat, double cutoff);
RcppExport SEXP _exactRra_matrix_binary_search(SEXP score_matSEXP, SEXP cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type score_mat(score_matSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_binary_search(score_mat, cutoff));
    return rcpp_result_gen;
END_RCPP
}
// trunc_it_cumsum_cpp
int trunc_it_cumsum_cpp(NumericVector max_j, int n);
RcppExport SEXP _exactRra_trunc_it_cumsum_cpp(SEXP max_jSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type max_j(max_jSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(trunc_it_cumsum_cpp(max_j, n));
    return rcpp_result_gen;
END_RCPP
}
// trunc_it_log_cumsum_cpp
double trunc_it_log_cumsum_cpp(NumericVector max_j, int n);
RcppExport SEXP _exactRra_trunc_it_log_cumsum_cpp(SEXP max_jSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type max_j(max_jSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(trunc_it_log_cumsum_cpp(max_j, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_exactRra_matrix_binary_search", (DL_FUNC) &_exactRra_matrix_binary_search, 2},
    {"_exactRra_trunc_it_cumsum_cpp", (DL_FUNC) &_exactRra_trunc_it_cumsum_cpp, 2},
    {"_exactRra_trunc_it_log_cumsum_cpp", (DL_FUNC) &_exactRra_trunc_it_log_cumsum_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_exactRra(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
