# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Binary search for each row in two-way monotonous matrix score_mat
#'
#' Matrix `score_mat` is a M * N matrix, which is monotonous in two ways in the
#' sense that score_mat[m, n] < score_mat[m, n + 1] and score_mat[m, n] >
#' score_mat[m + 1, n] for each 1 <= m <= M and 1 <= n <= N.
#'
#' @param score_mat A M * N matrix of values to be searched.
#' @param cutoff The cutoff value.
#' @return A vector J, where value J[m] is such that score_mat[m, n] <= cutoff
#' for n <= J[m] and score_mat[m, n] > cutoff for n > J[m]. Note that values in
#' J are 1-based.
#'
#' @md
#' @export
matrix_binary_search <- function(score_mat, cutoff) {
    .Call(`_exactRra_matrix_binary_search`, score_mat, cutoff)
}

#' Helper function for computing a truncated iterative cumulative sum.
#'
#' Let max_j = J be natural numbers 0 <= J[0] <= ... <= J[m] <= n.
#' The truncated iterative cumulative sum is defined as
#' sum_{i_{n-1} = J_{n-1}}^{n-1} sum_{i_{n-2} = J_{n-2}}^{J_{n-1}-1} ... sum_{i_0 = J_0}^{J_1-1} 1.
#'
#' @param max_j Natural numbers 0 <= max_j[1] <= ... <= max_j[m] <= n.
#' @param n The number of values to be cumulatively summed. See description.
#'
#' @return The calculated sum or log-sum.
#'
trunc_it_cumsum_cpp <- function(max_j, n) {
    .Call(`_exactRra_trunc_it_cumsum_cpp`, max_j, n)
}

#' @describeIn trunc_it_cumsum_cpp Helper function for
#' computing a truncated iterative cumulative log-sum.
#'
trunc_it_log_cumsum_cpp <- function(max_j, n) {
    .Call(`_exactRra_trunc_it_log_cumsum_cpp`, max_j, n)
}

